# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIChatFB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Kingfisher/SwiftUI'
  # Pods for SwiftUIChatFB

  target 'SwiftUIChatFBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIChatFBUITests' do
    # Pods for testing
  end

end
